### PR TITLE
Social, system-wide JavaScript packages and support for uglify-js

### PR DESCRIPTION
**Pull request by pmetras**
This pull request contains various changes:
- 3 new parameters in `myphotoshare.conf` to support display options for the social icons. One can select the icons to display with `social`, if they are coloured or not with `social_color` and their size with `social_size`.
- French translation for the new menu options in the top right UI menu.
- Support for new JavaScript minifyier `uglify-js` which is the default when creating Debian/Ubuntu packages.
- When system-wide JavaScript packages are installed, `js-css-minify.sh` and `index.php` will use them instead of the versions provided by MyPhotoShare. This feature can create non reproducible bugs if a user's system has different jQuery versions than the project's ones, but it also gives the user the opportunity to manage updates of jQuery libraries by the security team of the Linux distribution.
I've a mixed opinion about this change because ideally, shared JavaScript library should not be included in a project but should be declared mandatory requirements. But as JavaScript does not support modules for _traditional_ web apps, they are distributed in the app. In case of security issue in a library, the whole web app security depend on the author updating regularly the libraries...
- Corrected a bug in `index.php` where JSON boolean values are understood as string by PHP. Also values are not case sensitive.

### CODE REVIEW

**Comment by paolobenve** [comment]
good work! congratulations!

**Comment by paolobenve** [comment]
after merging and running the scanner, opening the web page I get a lot of errors like

```
Uncaught ReferenceError: jQuery is not defined
    at 001-hashchange.js:390
```
and the page doesn't finish loading

**Comment by paolobenve** [comment]
jquery error

**Comment by paolobenve** [comment]
it seems that is because the server must have a /javascript definition, perhaps the docs might say it

**Comment by pmetras** [comment]
That's strange because when a JavaScript library is installed on Ubuntu/Debian, a virtual directory `/javascript` is defined on the web server... I don't know how to test for the existence of that virtual directory. I'm testing the presence of the libraries on the file system. Perhaps a test with `wget` or `curl` in `js-css-minify.css` and with PHP functions in `index.php`?
Like I said, I'm not 100% sure this patch is a good idea...

**Pull request merged**
